services:
    _defaults:
        public: true
        autowire: true

    Symplify\EasyCodingStandard\SniffRunner\:
        resource: '../src'
        exclude: '../src/{Exception,File/File.php,Event}'
