language: php

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - bin/ecs
  - vendor/bin/phpunit

notifications:
  email: never
