language: php

matrix:
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.3
        - php: 7.4snapshot

install:
    - composer update --prefer-source $COMPOSER_FLAGS

script:
    - bin/ecs
    - vendor/bin/phpunit

notifications:
    email: false
