language: php

matrix:
    include:
        - php: 7.1
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
        - php: 7.3
          env: COMPOSER_FLAGS="--ignore-platform-reqs"

install:
    - composer update --prefer-source $COMPOSER_FLAGS

script:
    - bin/ecs
    - vendor/bin/phpunit

notifications:
    email: false
