services:
    _defaults:
        autowire: true

    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '..'
        exclude: '../{Exception}'

    Symfony\Component\Stopwatch\Stopwatch: ~

    # differ
    PhpCsFixer\Differ\UnifiedDiffer: ~

    Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor:
        public: true # for tests

    PhpCsFixer\WhitespacesFixerConfig:
        factory: ['@Symplify\EasyCodingStandard\FixerRunner\WhitespacesFixerConfigFactory', 'create']
