services:
    _defaults:
        public: true
        autowire: true

    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '../src'
        exclude: '../src/{Exception}'

    # differ
    PhpCsFixer\Differ\UnifiedDiffer: ~
    PhpCsFixer\Differ\DifferInterface: '@PhpCsFixer\Differ\UnifiedDiffer'

    Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor:
