imports:
    - { resource: 'php70.yaml' }

services:
    # All elements should have visibility
    PhpCsFixer\Fixer\ClassNotation\VisibilityRequiredFixer:
        elements: [const, property, method]

    # Turn list() into []
    PhpCsFixer\Fixer\ListNotation\ListSyntaxFixer:
        syntax: short

    # Nullable Typehints
    SlevomatCodingStandard\Sniffs\TypeHints\NullableTypeForNullDefaultValueSniff: ~
    PhpCsFixer\Fixer\Whitespace\CompactNullableTypehintFixer: ~

    # Void Typehints
    PhpCsFixer\Fixer\FunctionNotation\VoidReturnFixer: ~
