services:
    Symplify\EasyCodingStandard\:
        resource: '../../src'
        exclude: '../../src/{Contract,DependencyInjection,Exception,Error/Error.php,Error/FileDiff.php,Yaml}'

    Symplify\EasyCodingStandard\Console\Application:
        public: true

    _instanceof:
        Symplify\EasyCodingStandard\Contract\Application\FileProcessorCollectorInterface:
            calls:
                # orders matters, so Fixer can cleanup after Sniffer
                - ['addFileProcessor', ['@Symplify\EasyCodingStandard\SniffRunner\Application\SniffFileProcessor']]
                - ['addFileProcessor', ['@Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor']]
