imports:
    - { resource: '../packages/**/config/services.yaml' }
    - { resource: 'services.yaml' }
    # A. in monorepo
    - { resource: '../../CodingStandard/packages/TokenRunner/config/config.yaml', ignore_errors: true }
    # B. as dependency
    - { resource: '%vendor%/symplify/coding-standard/packages/TokenRunner/config/config.yaml', ignore_errors: true }

parameters:
    # defaults for "PhpCsFixer\WhitespacesFixerConfig"
    indentation: 'spaces'
    line_ending: \n

    cache_directory: '%sys_get_temp_dir%/_changed_files_detector%env(TEST_SUFFIX)%'
    cache_namespace: '%getcwd_webalized%'

    # checkers
    skip: []
    only: []

    file_extensions:
        - 'php'

    exclude_files: []
    # for tests
    env(TEST_SUFFIX): ''
