imports:
    # A. in monorepo
    - { resource: '../../TokenRunner/config/config.yml', ignore_errors: true }
    # B. as dependency
    - { resource: '%vendor%/symplify/token-runner/config/config.yml', ignore_errors: true }

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    # Console
    Symfony\Component\Console\Terminal: ~

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
    Symplify\PackageBuilder\FileSystem\FileGuard: ~
    Symplify\PackageBuilder\Php\TypeAnalyzer: ~

    PhpCsFixer\Tokenizer\Analyzer\NamespaceUsesAnalyzer: ~
    PhpCsFixer\Tokenizer\Analyzer\NamespacesAnalyzer: ~

    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symplify\PackageBuilder\EventSubscriber\ParameterTypoProofreaderEventSubscriber: ~
    Symplify\PackageBuilder\Parameter\ParameterTypoProofreader:
        $correctToTypos:
            # param => [typos]
            skip:
                - '#skip.{1}#'
                - 'exclude'
                - 'ignore'
            line_length:
                - 'line_lenght'
                - 'lineLength'
                - 'lineLenght'
                - 'line_size'
                - 'lineSize'
            exclude_checkers:
                - 'exclude_checker'
                - 'excluded_checker'
                - 'excluded_checkers'
                - 'skip_checker'
                - 'skip_checkers'
            exclude_files:
                - 'exclude_file'
                - 'excluded_file'
                - 'exclude_dir'
                - 'excluded_dir'
                - 'excluded_dirs'
                - 'exclude_path'
                - 'exclude_paths'
                - 'excluded_path'
                - 'excluded_paths'
                - 'skip_dirs'
                - 'skip_files'
