name: Fixer Test

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    fixer_test:
        runs-on: ubuntu-latest

        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.3'
                    coverage: none

            -   run: composer require phpunit/phpunit
                working-directory: ./tests

            -   run: composer require symplify/easy-coding-standard
                working-directory: ./tests

            -   run: vendor/bin/phpunit FixerTest.php
                working-directory: ./tests
